# robot_radius: 0.4 # distance a circular robot should be clear of the obstacle
footprint: [[ 0.9,  0.3], [-0.9,  0.3], [-0.9, -0.3], [ 0.9, -0.3]]
# footprint: [[ 0.15,  0.15], [-0.15,  0.15], [-0.15, -0.15], [ 0.15, -0.15]]
# footprint: [[-0.65,  -0.34], [-0.65, 0.34], [ 0.65, 0.34],[ 0.65,  -0.34]]
#
footprint_padding: 0.025
# robot_radius: 0.6

robot_base_frame: base_link

map_type: voxel

obstacle_layer:
  enabled:              true
  max_obstacle_height:  2.0 # assume something like an arm is mounted on top of the robot
  min_obstacle_height: -2.0
  obstacle_range: 10
  raytrace_range: 20
  origin_z:             0.0
  z_resolution:         0.1
  z_voxels:             5
  unknown_threshold:    15
  mark_threshold:       0
  combination_method:   1
  publish_voxel_map: false
  track_unknown_space: true
  footprint_clearing_enabled: true
  observation_sources: scan

  scan:
    data_type: PointCloud2
    topic: /rtabmap/local_grid_obstacle
    marking: true
    clearing: true
    # observation_persistence: 0.5
    expected_update_rate: 0.0 # Fix this
    max_obstacle_height: 2.0
    min_obstacle_height: 0.0


#cost_scaling_factor and inflation_radius were now moved to the inflation_layer ns
inflation_layer:
  enabled:              true
  cost_scaling_factor:  10.0  # 2.0 before exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     2.0 # 1.0 before - max. distance from an obstacle at which costs are incurred for planning paths.

static:
  enabled:              true
  track_unknown_space:  true
